---
apiVersion: v1
kind: Pod
metadata:
    name: gameoflife
spec:
    containers:
      - image: learningthoughts/gameoflife:01
        name: gol
        livenessProbe: 
          httpGet:
            path: /gameoflife
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        ports:
          - containerPort: 8080
            name: golhttpport
            protocol: TCP