---
apiVersion: v1
kind: Pod
metadata:
  name: podwithemptyvol
spec:
  containers:
    - image: learningthoughts/gameoflife:01
      name: gol-container
      volumeMounts:
        - mountPath: /temporary
          name: temporaryvolume
  volumes:
    - name: temporaryvolume
      emptyDir: {}