---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gol-dev
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: gol
      env: dev
  template:
    metadata:
      labels:
        app: gol
        env: dev
    spec:
      containers:
        - image: learningthoughts/gameoflife:01
          name: gol-dev
          ports:
            - containerPort: 8080
              protocol: TCP
    
    