---
apiVersion: batch/v1
kind: Job
metadata:
  name: ubuntu-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - image: ubuntu
          name: ubuntu-cont
          args:
            - /bin/bash
            - -c
            - sleep 10m
          ports:
            - containerPort: 8080
              protocol: TCP
  