---
apiVersion: v1
kind: Pod
metadata: 
    name: gol-pod
spec:
    containers: 
         - name: my-gol-cont
           image: learningthoughts/gameoflife:01
           ports: 
            - containerPort: 8080
