---
apiVersion: v1
kind: Pod
metadata:
    name: gameoflife
spec:
    containers:
      - image: learningthoughts/gameoflife:01
        name: gol
        ports:
          - containerPort: 8080
            name: golhttpport
            protocol: TCP